version: '3.6'
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - '61613:61613'
    environment:
      - RABBITMQ_PLUGINS=[rabbitmq_web_stomp]
#    command: ["rabbitmq-plugins enable rabbitmq_stomp"]

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: ["redis-server", "--requirepass admin"]

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
